apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: proyecto-ml
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web
  namespace: proyecto-ml
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web
