apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-green
  namespace: proyecto-ml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-green
  minReplicas: 0          # idle until promoted
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
